### PR TITLE
Fix reuse list tail exercise

### PR DESCRIPTION
**Pull request by dialelo**
Based on the work by @idarlington

### CODE REVIEW

**Comment by dialelo** [comment]
@raulraja please take a look.

**Comment by raulraja** [comment]
LGTM!

**Comment by idarlington** [comment]
Hi @dialelo thanks, concerning hanging `sbt test` you have any idea why and any solutions?

**Comment by dialelo** [comment]
Was your `sbt test` hanging? Weird. Compilation of tests is a bit slow since it uses Shapeless heavily but I've never experienced hanging tests, maybe tweaking the JVM settings can help?

**Comment by raulraja** [comment]
Try running `sbt -v test` and see what JVM args SBT is running with. It's most likely an OOM.

**Comment by raulraja** [comment]
Try running `sbt -v test` and see what JVM args SBT is running with. It's most likely an OOM.

**Comment by idarlington** [comment]
@dialelo @raulraja I set max heap size at 2G and it still hangs at this point 
```
[warn] 5 warnings found
[info] Compiling 37 Scala sources to /home/idarlington/Documents/REPOS/exercises-stdlib/target/scala-2.11/test-classes...
```

**Comment by raulraja** [comment]
What is the output of `sbt -v test` ?

**Comment by idarlington** [comment]
@raulraja this 
```
[process_args] java_version = '1.8.0_91'
# Executing command line:
java
-Xmx2G
-XX:+UseConcMarkSweepGC
-XX:+CMSClassUnloadingEnabled
-XX:MaxPermSize=2G
-Xss2M
-Duser.timezone=GMT
-jar
/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
```

**Comment by raulraja** [comment]
That seems fine. Try `sbt clean test`

**Comment by idarlington** [comment]
Still hangs.

**Comment by raulraja** [comment]
I can't repro that, perhaps with more info about your environment. Builds
fine on travis which are usually crappy machines, so must be something
related to your setup.

**Comment by idarlington** [comment]
I am runnning it on 
`Ubuntu 14.04`, 
`12GB RAM`,
 `sbt 0.13.7`, 
` java "1.8.0_91"`

**Comment by raulraja** [comment]
Can you try updating your sbt to the latest stable. That is an old version.
Not sure it matters since the launcher can fetch latest but in case.

**Comment by idarlington** [comment]
Hi, @raulraja , @dialelo  it works fine now, had to delete the local version and clone it again. Thanks for trying to resolve this with me.

**Comment by raulraja** [comment]
Cool!

**Pull request merged**
